exports.stores = [
  {name: 'Nike Oficial'},
  {name: 'Adidas Oficial'},
  {name: 'Jordan Oficial'},
  {name: 'New Balance Oficial'},
]

exports.shoes = [
{ name: 'Stan Smith All White',
  img: 'Stan-Smith-white.jpeg',
  price: 95,
  brand: 'Adidas',
  model: 'Stan Smith',
  releaseAt: new Date('Tue Jan 12 2010 00:00:00 GMT-0430 (hora de Venezuela)').getFullYear(),
  store: 'Adidas Oficial' 
},
{ name: 'Disney Hulk And Thor Stan Smith',
  img: 'Disney_Hulk_and_Thor_Stan_Smith_Black_GZ5993_01_standard.jpeg',
  price: 100,
  brand: 'Adidas',
  model: 'Stan Smith',
  releaseAt: new Date('Sat Aug 02 2014 00:00:00 GMT-0430 (hora de Venezuela)').getFullYear(),
  store: 'Adidas Oficial' 
},
{ name: 'Disney Monsters, Inc. Stan Smith',
  img: 'Disney_Monsters_Inc._Stan_Smith_White_GZ5990_01_standard.jpg',
  price: 100,
  model: 'Stan Smith',
  releaseAt: new Date('2022-12-02T04:00:00.000Z').getFullYear(),
  store: 'Adidas Oficial',
  brand: 'Adidas' 
},
{ name: 'Superstar White',
  img: 'Superstar_Vegan_Shoes_White_FW2295_01_standard.jpeg',
  price: 100,
  brand: 'Adidas',
  model: 'Superstar',
  releaseAt: new Date('Sat Mar 05 2005 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'Adidas Oficial' 
},
{ name: 'Superstar Black',
  img: 'Superstar_Vegan_Shoes_Black_FW2296_01_standard.jpeg',
  price: 100,
  brand: 'Adidas',
  model: 'Superstar',
  releaseAt: new Date('Sun Apr 09 2006 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'Adidas Oficial' 
},
{ name: 'Nike Air Max 95',
  img: 'Nike-air-max-95.jpg',
  price: 138,
  brand: 'Nike',
  model: 'Air Max',
  releaseAt: new Date('1995-07-10T04:00:00.000Z').getFullYear(),
  store: 'Nike Oficial' 
},
{ name: 'Nike Air Force 1 07 Craft',
  img: 'Nike-Air-Force-1-Craft.jpg',
  price: 120,
  brand: 'Nike',
  model: 'Air Force',
  releaseAt: new Date('Sat Feb 28 2009 00:00:00 GMT-0430 (hora de Venezuela)').getFullYear(),
  store: 'Nike Oficial' 
},
{ name: 'Nike Air Zoom Alphafly',
  img: 'Nike-Air-Zoom-Alphafly.jpg',
  price: 250,
  brand: 'Nike',
  model: 'Air Max',
  releaseAt: new Date('Sun Nov 20 2011 00:00:00 GMT-0430 (hora de Venezuela)').getFullYear(),
  store: 'Nike Oficial' 
},
{ name: 'Nike Air Max 270',
  img: 'Nike-Air-Max-270.jpg',
  price: 150,
  brand: 'Nike',
  releaseAt: new Date('Tue Mar 12 2019 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'Nike Oficial',
  model: 'Air Max' 
},
{ name: 'Nike Air Zoom Pegasus 38',
  img: 'Nike-Air-Zoom-Pegasus-38.jpg',
  price: 250,
  brand: 'Nike',
  model: 'Air Zoom',
  releaseAt: new Date('Thu Jul 15 2021 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'Nike Oficial' 
},
{ name: 'Nike ZoomX Vaporfly',
  img: 'Nike-ZoomX-Vaporfly.jpg',
  price: 200,
  brand: 'Nike',
  model: 'ZoomX',
  releaseAt: new Date('Sun Jan 05 2020 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'Nike Oficial' 
},
{ name: 'Nike Air VaporMax Plus',
  img: 'Nike-Air-VaporMax-Plus.jpg',
  price: 200,
  brand: 'Nike',
  model: 'Air VaporMAx',
  releaseAt: new Date('Sat Dec 21 2019 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'Nike Oficial' 
},
{ name: 'Nike Air Max 95 Essential',
  img: 'Nike-Air-Max-95-Essential.jpg',
  price: 170,
  brand: 'Nike',
  model: 'Air Max',
  releaseAt: new Date('Mon Apr 23 2018 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'Nike Oficial' 
},
{ name: 'Nike ZoomX Vaporfly NEXT 2',
  img: 'Nike-ZoomX-Vaporfly-NEXT-2.jpg',
  price: 120,
  brand: 'Nike',
  model: 'ZoomX',
  releaseAt: new Date('Mon Jul 24 2017 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'Nike Oficial' 
},
{ name: 'Nike Adapt BB 2.0',
  img: 'Nike-Adapt-BB-2.0.jpg',
  price: 150,
  brand: 'Nike',
  model: 'Adapt',
  releaseAt: new Date('Mon Jan 25 2016 00:00:00 GMT-0430 (hora de Venezuela)').getFullYear(),
  store: 'Nike Oficial' 
},
{ name: 'Nmd R1 Primeblue',
  img: 'NMD_R1_Primeblue_Shoes_White_GX8313_01_standard.jpeg',
  price: 150,
  brand: 'Adidas',
  model: 'Nmd',
  releaseAt: new Date('Tue May 12 2015 00:00:00 GMT-0430 (hora de Venezuela)').getFullYear(),
  store: 'Adidas Oficial' 
},
{ name: 'Nizza Hi Rf',
  img: 'Nizza_RF_Shoes_Burgundy_H01139_01_standard.jpeg',
  price: 90,
  brand: 'Adidas',
  model: 'Nizza',
  releaseAt: new Date('Tue Sep 24 2013 00:00:00 GMT-0430 (hora de Venezuela)').getFullYear(),
  store: 'Adidas Oficial' 
},
{ name: 'Nizza Rf',
  img: 'Nizza_Hi_RF_Shoes_Burgundy_H01145_01_standard.jpeg',
  price: 80,
  brand: 'Adidas',
  model: 'Nizza',
  releaseAt: new Date('Sat Mar 31 2012 00:00:00 GMT-0430 (hora de Venezuela)').getFullYear(),
  store: 'Adidas Oficial' 
},
{ name: 'Nizza Rf Slip',
  img: 'Nizza_RF_Slip_Shoes_White_S23725_01_standard.jpeg',
  price: 65,
  brand: 'Adidas',
  model: 'Nizza',
  releaseAt: new Date('Wed May 25 2011 00:00:00 GMT-0430 (hora de Venezuela)').getFullYear(),
  store: 'Adidas Oficial' 
},
{ name: 'Forum Mid',
  img: 'Forum_Mid_Shoes_White_GX5054_01_standard.jpeg',
  price: 77,
  brand: 'Adidas',
  model: 'Mid',
  releaseAt: new Date('Sat Dec 22 2007 00:00:00 GMT-0430 (hora de Venezuela)').getFullYear(),
  store: 'Adidas Oficial' 
},
{ name: 'Fresh Foam X 860v12',
  img: 'Fresh-Foam-X-860v12.webp',
  price: 135,
  brand: 'New Balance',
  model: 'Foam',
  releaseAt: new Date('Mon Nov 21 2016 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'New Balance Oficial' 
},
{ name: 'Fresh Foam Roav',
  img: 'Fresh-Foam-Roav.webp',
  price: 85,
  brand: 'New Balance',
  model: 'Foam',
  releaseAt: new Date('Thu Oct 21 2010 00:00:00 GMT-0430 (hora de Venezuela)').getFullYear(),
  store: 'New Balance Oficial' 
},
{ name: 'Fresh Foam Cruzv1 Reissue',
  img: 'Fresh-Foam-Cruzv1-Reissue.webp',
  price: 85,
  brand: 'New Balance',
  model: 'Foam',
  releaseAt: new Date('Thu Jan 21 1999 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'New Balance Oficial' 
},
{ name: 'NB Numeric 272',
  img: 'NB-Numeric-272.webp',
  price: 75,
  brand: 'New Balance',
  model: 'NB',
  releaseAt: new Date('Sat Sep 28 1996 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'New Balance Oficial' 
},
{ name: 'FuelCell Shift Tr',
  img: 'FuelCell-Shift-TR .webp',
  price: 100,
  brand: 'New Balance',
  model: 'Shift',
  releaseAt: new Date('2012-10-03T04:30:00.000Z').getFullYear(),
  store: 'New Balance Oficial' 
},
{ name: 'Air Jordan 1 Low',
  img: 'Air-Jordan-1-Low .webp',
  price: 182,
  brand: 'Jordan',
  model: 'Air Low',
  releaseAt: new Date('Sun Jan 30 2022 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'Jordan Oficial' 
},
{ name: 'Air Jordan 1 Mid ',
  img: 'Air-Jordan-1-Mid .webp',
  price: 208,
  brand: 'Jordan',
  model: 'Air Mid',
  releaseAt: new Date('Tue Jun 15 2021 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'Jordan Oficial' 
},
{ name: 'Air Jordan 4 Retro "White Oreo"',
  img: 'Air-Jordan-4-Retro-"White-Oreo".webp',
  price: 540,
  brand: 'Jordan',
  model: 'Retro 4',
  releaseAt: new Date('Sun Feb 14 2021 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'Jordan Oficial' 
},
{ name: 'Air Jordan 1 Retro High J. Balvin "Colores y Vibras"',
  img: 'Air-Jordan-1-Retro-High-J-Balvin.webp',
  price: 514,
  brand: 'Jordan',
  model: 'Air High',
  releaseAt: new Date('Tue Jul 20 2021 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'Jordan Oficial' 
},
{ name: 'Air Jordan 11 Retro legend blue',
  img: 'Air-Jordan-11-Retro-legend-blue.webp',
  price: 642,
  brand: 'Jordan',
  model: 'Air Retro',
  releaseAt: new Date('Sun Apr 25 2021 00:00:00 GMT-0400 (hora de Venezuela)').getFullYear(),
  store: 'Jordan Oficial'
}
]